<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>RoburPseudoCommands</RootNamespace>
    <AssemblyName>RoburPseudoCommands</AssemblyName>
    <Version>0.8.0</Version>
    <AssemblyVersion>0.8.0.0</AssemblyVersion>
    <FileVersion>0.8.0.0</FileVersion>
    <InformationalVersion>0.8.0-rc.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <LangVersion>7.3</LangVersion>
    <RoburInstallDir Condition="'$(RoburInstallDir)' == ''">C:\Program Files\Topomatic Robur Road 16.0</RoburInstallDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" GeneratePathProperty="true" />
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="Topomatic.ApplicationPlatform">
      <HintPath>$(RoburInstallDir)\Topomatic.ApplicationPlatform.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Cad.Foundation">
      <HintPath>$(RoburInstallDir)\Topomatic.Cad.Foundation.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Cad.View">
      <HintPath>$(RoburInstallDir)\Topomatic.Cad.View.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Controls">
      <HintPath>$(RoburInstallDir)\Topomatic.Controls.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Dwg">
      <HintPath>$(RoburInstallDir)\Topomatic.Dwg.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.FoundationClasses">
      <HintPath>$(RoburInstallDir)\Topomatic.FoundationClasses.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Dwg.Layer">
      <HintPath>$(RoburInstallDir)\Topomatic.Dwg.Layer.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Maps">
      <HintPath>$(RoburInstallDir)\Topomatic.Maps.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Topomatic.Sfc">
      <HintPath>$(RoburInstallDir)\Topomatic.Sfc.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <None Remove="DiagnosticsSDK\**\*" />
    <None Include="$(PkgLib_Harmony)\LICENSE" Link="Harmony-LICENSE.txt" CopyToOutputDirectory="Always" />
    <None Include="RoburPseudoCommands.plugin" CopyToOutputDirectory="Always" />
    <None Include="aliases.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Icons\**\*.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
